// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaftZxVPBOGCWMocaBPLWdEUF3d7IckDg',
    appId: '1:421781211919:web:3ce1a979af5bc957f6cc7a',
    messagingSenderId: '421781211919',
    projectId: 'stockmate-94582',
    authDomain: 'stockmate-94582.firebaseapp.com',
    storageBucket: 'stockmate-94582.firebasestorage.app',
    measurementId: 'G-199KQ4KGRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_k6T_SLu9D6d7MhDl70Je80kQejt8A84',
    appId: '1:421781211919:android:5072ca37aa4dfb9ff6cc7a',
    messagingSenderId: '421781211919',
    projectId: 'stockmate-94582',
    storageBucket: 'stockmate-94582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWo31l7d22utdLhx1YvgMp8bQnpcZAmY',
    appId: '1:421781211919:ios:7cc3f68be7040932f6cc7a',
    messagingSenderId: '421781211919',
    projectId: 'stockmate-94582',
    storageBucket: 'stockmate-94582.firebasestorage.app',
    iosBundleId: 'com.example.stockmateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMWo31l7d22utdLhx1YvgMp8bQnpcZAmY',
    appId: '1:421781211919:ios:7cc3f68be7040932f6cc7a',
    messagingSenderId: '421781211919',
    projectId: 'stockmate-94582',
    storageBucket: 'stockmate-94582.firebasestorage.app',
    iosBundleId: 'com.example.stockmateapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaftZxVPBOGCWMocaBPLWdEUF3d7IckDg',
    appId: '1:421781211919:web:1e701f3256da19faf6cc7a',
    messagingSenderId: '421781211919',
    projectId: 'stockmate-94582',
    authDomain: 'stockmate-94582.firebaseapp.com',
    storageBucket: 'stockmate-94582.firebasestorage.app',
    measurementId: 'G-D6X01DH3BN',
  );
}
